---
abstract: "AYOUNG's default Pod::Weaver config"
author:
  - 'Alan Young <harleypig@gmail.com>'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::Perl::Critic::Progressive: 0
  Try::Tiny: 0
  perl: 5.004
configure_requires:
  ExtUtils::MakeMaker: 6.31
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102346, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Weaver-PluginBundle-AYOUNG
no_index:
  directory:
    - t
    - xt
provides:
  Pod::Weaver::PluginBundle::AYOUNG:
    file: lib/Pod/Weaver/PluginBundle/AYOUNG.pm
    version: 0.11
requires:
  Pod::Weaver::Config::Assembler: 0
resources:
  bugtracker: http://github.com/harleypigs/pod-weaver-pluginbundle-ayoung/issues
  repository: git://github.com/harleypig/pod-weaver-pluginbundle-ayoung.git
version: 0.11
